---
- name: Configuracion_Cisco_ACI
  hosts: AP-ASR99K-CORE-1
  gather_facts: no
  connection: ansible.netcommon.network_cli  
  
  
  tasks:
    - name: Crear Bundle-Ethernet_10191    
      cisco.iosxr.iosxr_config:
        src: "{{ playbook_dir }}/AP-CORE_BE10191_26042022.txt"

      register: BundleEth_10191

    - name: ImprimirConfig
      debug: var=BundleEth_10191