---
- name: Configuracion_BE_LM-PE
  hosts: LM-PE
  gather_facts: no
  connection: ansible.netcommon.network_cli  
  
  
  tasks:
    - name: Crear BE    
      cisco.iosxr.iosxr_config:
        src: playbook_dir + '/Config_BE_Netflix.txt'

      register: BundleEth

    - name: ImprimirConfig
      debug: var=BundleEth
