---
- name: Configuracion_BE_LM-PE
  hosts: localhost
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Crear BE
      cisco.iosxr.iosxr_config:
        
        lines:
          
          - description ##CDN## NETFLIX c001.eze009.telecentro.isp (190.55.32.161-2800:810:202::1e)
          - l2transport
          - shut 
          - commit
          parents: interface Bundle-Ether40027
          
          
          - description ##CDN## NETFLIX c002.eze009.telecentro.isp (190.55.32.162-2800:810:202::1f)
          - l2transport
          - shut
          - commit
          parents: interface Bundle-Ether40028
          
          

      register: BundleEth

    - name: ImprimirConfig
      debug: var=BundleEth
          
