---
- name: Configuracion_BE_LM-PE
  hosts: LM-PE
  gather_facts: no
  connection: ansible.netcommon.network_cli

  tasks:
    - name: Crear BE
      cisco.iosxr.iosxr_config:
        save_when: modified
        config:
        lines:
        - description ##CDN## NETFLIX c001.eze009.telecentro.isp (190.55.32.161-2800:810:202::1e)
        - l2transport
        - shut 
        parents: interface Bundle-Ether40027
      when: ansible_network_os == 'cisco.iosxr.iosxr_config'
      register: BundleEth

    - name: ImprimirConfig
      debug: var=BundleEth
